using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Caffoa;
using DemoV2.AspNet.Model.Base;
using DemoV2.AspNet.Model;

namespace DemoV2.AspNet;

/// AUTOGENERATED BY caffoa
/// <summary>
/// Controller to be implemented to serve the api
/// </summary>
[ApiController]
[Route("api")]
public class DemoV2AspNetMaintainanceController : ControllerBase
{
    private readonly ICaffoaFactory<IDemoV2AspNetMaintainanceService> _factory;
    
    public DemoV2AspNetMaintainanceController(ICaffoaFactory<IDemoV2AspNetMaintainanceService> factory)
    {
        _factory = factory;
    }
    public IDemoV2AspNetMaintainanceService GetService() => _factory.Instance(Request);

    /// <summary>
    /// start a long running function via durable functions
    /// 202 -> started long running function
    ///</summary>
    [HttpPost("startLongRunningFunction/{id}")]
    public async Task<ActionResult<ASPLongRunningfunctionStatus>> LongRunningFunctionAsync([FromRoute] Guid id, CancellationToken cancellationToken = default) { return StatusCode(202, await GetService().LongRunningFunctionAsync(id, cancellationToken)); }


}