using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
{IMPORTS}
namespace {NAMESPACE};

/// AUTOGENERATED BY caffoa
/// <summary>
/// Controller to be implemented to serve the api
/// </summary>
[ApiController]
[Route("{BASEPATH}")]
public class {CLASSNAME} : ControllerBase
{{
   // *** Caffoa insertion point. New Methods will be inserted above this comment by caffoa. ***
}}