name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Execute caffoa
        run: CdIts.Caffoa.Cli/bin/Release/net7.0/CdIts.Caffoa.Cli
      - name: Build with changes
        run: dotnet build --configuration Release --no-restore
      - name: Tests
        run: dotnet test --no-restore --verbosity minimal
        
