using System;
using System.IO;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Caffoa;
using DemoV2.AspNetNewtonSoft.Model.Base;
using DemoV2.AspNetNewtonSoft.Model;

namespace DemoV2.AspNetNewtonSoft
{
    /// AUTOGENERATED BY caffoa
    /// <summary>
    /// Interface for services to be implemented to serve the Function implementation
    /// </summary>
    public interface IDemoV2AspNetNewtonSoftMaintainanceService
    {
        /// <summary>
        /// start a long running function via durable functions
        /// 202 -> started long running function
        /// </summary>
        Task<ASPNLongRunningfunctionStatus> LongRunningFunctionAsync(Guid id, CancellationToken cancellationToken = default);

    }
}
